### ISSUE TITLE
"X more" button looks out of place in new dark theme

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroHello#101]
![image](https://user-images.githubusercontent.com/1342360/47256244-d63aa180-d47c-11e8-8a5a-4cbba4675650.png)

It has a gradient while everything else is flat. I recommend just making a bit lighter color than the background, that's all.

**Comment by HelloZeroNet** [comment]
Thanks, fixed: https://github.com/HelloZeroNet/ZeroHello/commit/97a4a317d34ef9f55c6837c72141d5d1bb452571

**Comment by anoadragon453** [comment]
Looks good, thanks!
