### ISSUE TITLE
Instant search "in connected sites" can cause slowdown when want to search in 1 site only?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroHello#106]
Hello,

i got an impression that the instant search (ZeroHello newsfeed - Search in connected sites) may significantly increase search time when i want to search just one particular site. (phraseHere site:zerotalk), because it begin search query to all sites, immediately when i start typing. Here i am unsure how fast this first search gets terminated.

Why i think this is an issue?
When you are having a HDD and hundreds of "connected sites" (this is NOT a future, this is present situation) all sites search usually takes more than a minute ([in my case 3 minutes](https://github.com/HelloZeroNet/ZeroNet/issues/1226)) and one site search usually a few seconds.

How to solve issue:
A) disabling instant search by default
B) add bigger delay after stop typing (2sec.?)

**Comment by HelloZeroNet** [comment]
Other required thing is be able to cancel previous query.
