### ISSUE TITLE
[Question] Database vs User Data.json files

### ISSUE THREAD

**Issue by mishfit** [HelloZeroNet/ZeroHello#11]
From what I can tell given ZeroTalk and ZeroMe (and the documentation) the database is simply a copy of values stored in `data.json` files for each particular user.

Can one use the `data.json` file or the database independently of each other?

For instance, can one have a standalone database and no data.json files? Or can one have data.json files without a database?

**Comment by HelloZeroNet** [comment]
You can't have database without .json files, but you can read .json files without database (fileGet api command), but if you have many files it will be slow and complicated.
