### ISSUE TITLE
[ZeroHello] Websocket callback not found

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroHello#114]
I have a warning message in the new ZeroHello. I am pretty sure it is no big deal.

```javascript
[ZeroHello] Websocket callback not found: 
Object { to: 180, cmd: "response", result: "Updated", id: 618 }
```

**Comment by HelloZeroNet** [comment]
Thanks, it's not a real error: it's happens if there is no callback function defined for a function that has a callback.
In this case (https://github.com/HelloZeroNet/ZeroHello/blob/master/js/PageSites/Site.coffee#L89) it's not necessary as the update process display is handled by other way.
