### ISSUE TITLE
ERROR    Site:1HeLLo..Tf3D WebSocket handleRequest error: TypeError: delete() takes exactly 1 argument (2 given) in UiWebsocket.py line 83 > UiWebsocket.py line 267 > UiWebsocket.py line 934 > SitePlugin.py line 43

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroHello#115]
```
ERROR    Site:1HeLLo..Tf3D WebSocket handleRequest error: TypeError: delete() takes exactly 1 argument (2 given) in UiWebsocket.py line 83 > UiWebsocket.py line 267 > UiWebsocket.py line 934 > SitePlugin.py line 43 
 {"cmd":"siteDelete","params":{"address":"1G8VW......"},"wrapper_nonce":"..................","id":11}
```

Hello, i see this error whenever i attempt to delete that site via ZeroHello.
I visited that site, found to be bad. The site was added to the blocklist site. And i then attempted to delete the site via ZeroHello (the 1G8VW.. site was updating at that time), site disappeared but when i reload ZeroHello, it is still there. And above errors appear.

rev3850, Windows, Firefox

**Comment by HelloZeroNet** [comment]
Do you have any non-standard plugin enabled?

**Comment by slrslr** [comment]
@HelloZeroNet maybe PeerMessage, so i quit zeronet, disabled it and started it again. Issue stays same.
Current plugin list [is here](https://snag.gy/wDOEtg.jpg)

**Comment by HelloZeroNet** [comment]
I just checked and I was unable to reproduce it. Actually I don't have `SitePlugin.py` file in my src or plugins directory. Can you please search for it?

**Comment by slrslr** [comment]
SitePlugin.py file i have in:
ZeroNet\core\plugins\BackgroundProcessing
ZeroNet\core\plugins\disabled-PeerMessage
ZeroNet\core\plugins\disabled-PeerMessageNotConnecting
not in any other, parent directories... let me know if i need to try something.

**Comment by HelloZeroNet** [comment]
The it's because of the BackgroundProcessing plugin, which is not part of the standard distribution

**Comment by slrslr** [comment]
That was it, i disabled it by renaming the plugin folder and after zeronet restart, deleting works. Thank you.
I assume there is no way the log entry can indicate name of the pluign which caused the error..
