### ISSUE TITLE
Detect browser's color theme

### ISSUE THREAD

**Issue by filips123** [HelloZeroNet/ZeroHello#117]
There are currently "dark" and "light" color themes supported and users can configure time from ZeroHello or config file.

It should also be possible to use option "default" (or something like that) that would detect the browser's color theme and use it. This would be better because users won't have to set color theme multiple times (for system, browser and ZeroNet separately).

So, there should be three options in ZeroHello or config file. There should be options "dark" and "light" that would force the selected theme. There should also be third (but probably first in list and selected by default) option "default" that would use the browser's color theme (and fallback to light if detection isn't supported).

You should use `prefers-color-scheme` CSS media feature. It is currently only supported in Firefox 67+ and Safari but it will probably be implemented in other browsers.

You can detect it in [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) or with [JavaScript](https://medium.freecodecamp.org/how-to-detect-a-users-preferred-color-scheme-in-javascript-ec8ee514f1ef).

**Comment by filips123** [comment]
I will try to create this but I need some help.

Because this detection must happen in the client side, I created new CoffeeScript file that is included in `wrapper.html`. It correctly detects theme and theme changes but I have some problems.

To update the theme, three things need to be updated. First is `background-color` of the main page and the second is `theme-*` class in its body. This two things works. But `theme-*` also have to be updated in the site in an iframe. I also tried to do this, but the problem is that I get cross-origin when I want to change the class of body in the iframe.

@HelloZeroNet How can I do this? Is there some function in ZeroFrame to inject script (that would change the body's class) into iframe page? Any other alternative?

**Comment by HelloZeroNet** [comment]
Probably the cleanest solution would be let the sites handle it.

Other possibility: At the load of the wrapper it checks if the system preference is different from zeronet setting. If it is, then change it and reload the page.

**Comment by filips123** [comment]
> Probably the cleanest solution would be let the sites handle it.

But the problem is that all sites would need to be updated to do this. 

> Other possibility: At the load of the wrapper it checks if the system preference is different from zeronet setting. If it is, then change it and reload the page.

How could then wrapper detect if the user wants automatic theme changes? If this option would be overwritten every time there is an update, wrapper won't be able to detect if the user wants automatic theme changes.

This may be fixed by settings another user setting (maybe called `use_system_theme`) that would be independent of the current theme setting. So wrapper would only check for the system preference if that setting would be true.

Some problem with this may be if the user changes its system theme when the site is already opened. If the site would then be reloaded, the user could lose all their unsaved work. If it would not be reloaded, the theme would not be updated.

But this is probably not so important problem because users probably won't change system theme when they have sites opened. And if they would, they will just have to reload site manually.

If this is OK, I can develop support for this.

**Comment by HelloZeroNet** [comment]
Yeah adding a new, separate use_system_theme setting to the user sounds like a good solution. I think real-time theme changing is not a problem.

**Comment by filips123** [comment]
@HelloZeroNet I created PR HelloZeroNet/ZeroNet#1999.

When you merge it, please let me know which revision and version will it have, so I can implement version check and configuration in ZeroHello.

**Comment by HelloZeroNet** [comment]
The rev got bumped to 4085, so you can use that as a minimal version requirement

**Comment by filips123** [comment]
@HelloZeroNet Thank you. And which version will it be?

**Comment by HelloZeroNet** [comment]
0.7.0, but the version does not matter, it's safe to use `Page.site_info.rev > 4085`

**Comment by filips123** [comment]
I wanted version to display it to user (You need at least x.y.z to use this feature).

**Comment by filips123** [comment]
@HelloZeroNet I created #119.
