### ISSUE TITLE
Zites sorted in the wrong order

### ISSUE THREAD

**Issue by geekless** [HelloZeroNet/ZeroHello#120]
Since we have "Connecting Sites" in the left bar now, and those sites have many properties `undefined`, it breaks the sorting algorithm.

The issue is in method [SiteList.sortRows()](https://github.com/HelloZeroNet/ZeroHello/blob/master/js/PageSites/SiteList.coffee#L29).

Undefined values should be converted to numbers with `or 0` before comparing them, in the same way as it is already done for `sites_orderby == "addtime"` mode.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed by https://github.com/HelloZeroNet/ZeroHello/commit/bd47713faf376228d4775c10194ef3935ef6a3ee
