### ISSUE TITLE
A JavaScript error occurred while not subscribing to the site.

### ISSUE THREAD

**Issue by lsby** [HelloZeroNet/ZeroHello#121]
I apologize for my English, this is Google Translate.
Hello, I downloaded the latest window client from the official website, it automatically opened `http://127.0.0.1:43110 / 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D` in my browser, it should be this project.
As shown, it looks a bit unusual. The right side is empty, and clicking the "Settings" button does not respond.
![err](https://i.loli.net/2019/07/06/5d1fb7f1a8f7795738.png)
I got this error from the console.
```
all.js?lang=zh&site_modified=1562292014:2758 Uncaught TypeError: Cannot read property 'date_added' of undefined
    at FeedList.render (all.js?lang=zh&site_modified=1562292014:2758)
    at Array.<anonymous> (all.js?lang=zh&site_modified=1562292014:2189)
    at doRender (all.js?lang=zh&site_modified=1562292014:920)
FeedList.render @ all.js?lang=zh&site_modified=1562292014:2758
(anonymous) @ all.js?lang=zh&site_modified=1562292014:2189
doRender @ all.js?lang=zh&site_modified=1562292014:920
requestAnimationFrame (async)
scheduleRender @ all.js?lang=zh&site_modified=1562292014:928
(anonymous) @ all.js?lang=zh&site_modified=1562292014:2968
ZeroFrame.onMessage @ all.js?lang=zh&site_modified=1562292014:6691
(anonymous) @ all.js?lang=zh&site_modified=1562292014:6636
postMessage (async)
Wrapper.sendInner @ all.js?rev=3864&lang=zh:1607
Wrapper.onMessageWebsocket @ all.js?rev=3864&lang=zh:1023
(anonymous) @ all.js?rev=3864&lang=zh:921
```
Although I can connect to other websites, clicking the Settings button is useless.

The query found 2758 rows in all.js
```
      if (this.feeds && Page.settings.date_feed_visit < this.feeds[0].date_added) {
        this.saveFeedVisit(this.feeds[0].date_added);
      }
```
When `this.feeds` is an empty array, accessing `this.feeds[0] .date_added` will report an error. You should check if the length of `this.feeds` is 0.
When I subscribe to the source site, the problem disappears.
The query submission record found that `44e66fc9b7870fb62a49df2a7b5a2f4a9c983d16` joined this line.
I am not sure how to write CoffeeScript and merge it into `all.js`. If anyone notices this, please fix this error.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, should be fixed by this: https://github.com/HelloZeroNet/ZeroHello/commit/070516782c3817a2eb35c28f477f84116bf043a2
