### ISSUE TITLE
[Feature request] Do not show link to "Configuration" in menu if the plugin "UiConfig" is disabled

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroHello#126]
Hi,

I have disabled plugin `UiConfig` because I do not need it. When I go to menu tab I see link to `Configuration`. When I click I get 404 (plugin disabled).

Could you please hide link to `Configuration` in menu if plugin `UiConfig` has been disabled?

The same with `UiPluginManager`. If i disable that plugin I still see link to `Plugins` in tab and `ContentFilter` - link to `Manage blocked users and sites`

**Comment by HelloZeroNet** [comment]
Now it should hide Configuration menu if the UiConfig plugin is disabled: https://github.com/HelloZeroNet/ZeroHello/commit/98e1040537da016f8ca6d90616fe7ca4a4aab7f3
