### ISSUE TITLE
[Feature request] Show link to "Shut down ZeroNet" only if you have an admin permission

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroHello#127]
Hi,

I use multiuser plugin. When I am not logged in as an admin I see link in menu `Shut down ZeroNet`. Will be great to show this link only for admins

**Comment by HelloZeroNet** [comment]
Now it should hide the shutdown menu item if there is no permission for that (updating ZeroNet to latest rev also necessary): https://github.com/HelloZeroNet/ZeroHello/commit/98e1040537da016f8ca6d90616fe7ca4a4aab7f3
