### ISSUE TITLE
Collapsible categories in site list to allow faster navigation

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroHello#133]
**Currently i have to scroll 6 pages to see the "Connected sites:" section on ZeroHello so i can find most recently updated sites in this section. So this is not optimal.**

Suggestions:
A) make categories collapsed by default (can it speed up zerohello load time?) - at minimum, it is good idea in case of favorite, owned and connecting sites since you remember site name and usually open it just by entering the name in web browser address bar.
B) move "Connecting sites:" below "Connected" (in my case it would save me 3 pages of scrolling)?

**Comment by HelloZeroNet** [comment]
I just added collapsible categories to the sites lists by clicking on the category name. None of them are collapsed by default, but it's got saved to you profile, so you can customize on your needs and it will stay the same after refresh. https://github.com/HelloZeroNet/ZeroHello/commit/d063ba6d0f97d379d5977f374628a240c7373903

**Comment by slrslr** [comment]
Thank you for this UI improvement. Site list is much more handy now.
