### ISSUE TITLE
Prevent trackers drop-down list from growing font size in landscape.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroHello#151]
![Screenshot_20201101-145128](https://user-images.githubusercontent.com/43807387/97812780-c9e3a480-1c51-11eb-952b-30a0d21d8aea.png)
The above is the correct text size. IPv6 addresses are fully readable, but below is too large of a font size and the IPv6 address overlaps the announcement success text.
![Screenshot_20201101-145144](https://user-images.githubusercontent.com/43807387/97812818-10390380-1c52-11eb-9dab-bdacb63d4ac1.png)

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I have added a modification that removes the "Announced in" part (only displays the seconds), so it should not overlap now.

https://github.com/HelloZeroNet/ZeroHello/commit/e03a6ee1f0bbaee74e6bb2eb66fcfe315843d84d

**Comment by styromaniac** [comment]
Please re-open this issue. As I said in OP, the font size needs to not grow larger in landscape.

![Screenshot_20201129-192342](https://user-images.githubusercontent.com/43807387/100557631-6e203180-3278-11eb-9db6-c47840d337d6.png)
