### ISSUE TITLE
[Proposal]: Read FeedList limits from localStorage

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroHello#42]
The two limits (3 days and 10 post) is hardcoded in FeedList.coffee.
Is it possible to save and load limits from localStorage? 
Eg. {"sites_orderby":"peers","feedlist_limit": 100, "feedlist_day_limit": 30}

**Comment by HelloZeroNet** [comment]
Now ZeroHello auto loads older entries when you scroll to the bottom. I think this will satisfies your need.

**Comment by jaros1** [comment]
Thank you. Endless scroll is always nice. One of the reasons for using ZeroMe and not ZeroMePlus.
I forgot something in my issue text. The reason for I looks into this was because the newfeed disappeared for some "inactive" users and I checked the implementation. 
Will newfeed still disappear for inactive users?
