### ISSUE TITLE
[Feature Request] Serach filter

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroHello#47]
I can narrow my results by site in Google, just use `site: [domain]` , but I can't do that in ZeroHello.
This is useful, because I connected too many site to search (very slow), but I know which site they(the contents which I wan't to find) exist.

**Comment by slrslr** [comment]
Yes, operators like:
-site:ZeroTalk +site:NullPaste +mustcontain -mustnotcontain may contain "exact phrasse"

**Comment by HelloZeroNet** [comment]
`hello site:zerotalk` search got implemented some months ago

**Comment by lezsakdomi** [comment]
This feature is not indicated for the user (at least I should have to check this issue).

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 
ZeroHello could have a link near the search input, showing the available filters for search
