### ISSUE TITLE
[Bug] pt-br language isn't working

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroHello#49]

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed! https://github.com/HelloZeroNet/ZeroHello/commit/a6b506e7df61f7644f803a3fd27e8335b82ca4f1 (The pt-br.json file was saved with [UTF8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark), removing it solved the parse error)

**Comment by Plasmmer** [comment]
Can it be because I use Notepad in Windows? :stuck_out_tongue:

**Comment by ysc3839** [comment]
@Plasmmer Yes. I suggest you use [Notepad++](https://notepad-plus-plus.org/)
