### ISSUE TITLE
[Enchancement] Show most used OS/Browsers near the geocity globe

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroHello#54]

**Comment by HelloZeroNet** [comment]
ZeroNet does not stores/distributes your os/browser anywhere, so it's not possible

**Comment by Plasmmer** [comment]
Then why the locations works in the globe graphic?

**Comment by HelloZeroNet** [comment]
The ips are recorded, as in any P2P you have to know the peers currently seeding the content to be able to access it.
So all we have is IP and port.
