### ISSUE TITLE
cmdp throws a type error if there is no response

### ISSUE THREAD

**Issue by Wieke** [HelloZeroNet/ZeroHello#68]
Hi 

So I just saw that ZeroFrame.js now has promises, which is nice, but I think the implementation might be a tiny bit broken. I just did the following:

1. Create a new zite
 2. Insert `page.cmdp("certSelect", {}).then(x => { debugger; });` into line 43 (just before the end of the script tag).
3. Refresh the new zite
4. Select a cert
5. See a type error appear in the console

So I checked out the code behind the `cmdp` function and found `if (res.error) {` which would break when `res` doesn't exist. Now I don't know what the real problem is, whether `res` really should exist or not when calling `certSelect` or if `cmdp` should be able to deal with getting no response. (Worked around it by changing the line to `if (res && res.error) {`)

Cheers,

Wieke

**Comment by HelloZeroNet** [comment]
Hi, thanks for reporting, this should fix it: https://github.com/HelloZeroNet/ZeroHello/commit/d8ca246158d978ddbd4dbc092439f41c45fc6597
