### ISSUE TITLE
can not navigate with keyboard anymore (search field has always focus)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [HelloZeroNet/ZeroHello#8]
After this (1) was added to ZeroHello, 
the only possibility to navigate on here (2) is via the mouse :-(

scrolling with mouse is slower for me than using keys:
e.g. page-down, cursor-down do not work anymore
and when I type a character it uses it as a search which limits/changes the info on the page

I tried also by clicking with the mouse outside of the search field

browser: palemoon 26.2.1
ZN version 0.3.7 1232

(1) https://github.com/HelloZeroNet/ZeroNet/issues/419
(2) http://127.0.0.1:43110

**Comment by HelloZeroNet** [comment]
fixed 7eeb4598e7ae1b63dd8907da18b6ee56dc63fc7e
