### ISSUE TITLE
[Feature request] Filter not just by name but by address too

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroHello#81]
Hello,

on ZeroHello i am missing option to filter the sites list not just by name, but by entering zite address (public key)

next thing i am missing is a button on the right of the filtering field (inside it, maybe semi-transparent) which would clear the search field in one click and cause to remove filtering of the zite list. Same in Search field that filters news feed.

**Comment by HelloZeroNet** [comment]
Both added in latest changes
