### ISSUE TITLE
When selecting SK language throwing error

### ISSUE THREAD

**Issue by Biosias** [HelloZeroNet/ZeroHello#93]
After last update to SK translation is throwing :

"Internal error: ValueError: Expecting property name: line 57 column 1 (char 4494)
UiWebsocket.py line 81 > UiWebsocket.py line 268 > UiWebsocket.py line 1003 > Translate.py line 31 > Translate.py line 38 > __init__.py line 291 > __init__.py line 339 > decoder.py line 364 > decoder.py line 380"

when selecting it.

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed: https://github.com/HelloZeroNet/ZeroNet/commit/b6424b4596cd97846d9064852112653b7d8f158b (the problem was in the client's translation file)
